// 后台数据集定义：每个集合对应仓库中的一个 JSON 文件。
// fields.type：text / number / textarea / lines（每行一条）/ select
// select.ref 指向另一集合，用于下拉选择（如排行榜选择玩家）。
export const REPO_DEFAULT = {
  owner: "JeffreyMing2004",
  repo: "mctzz-web",
  branch: "main",
};

export const COLLECTIONS = [
  {
    key: "episodes",
    label: "往期内容",
    file: "src/data/episodes.json",
    hasId: true,
    list: ["title", "air_date", "status"],
    fields: [
      { key: "title", label: "标题", type: "text", required: true },
      { key: "description", label: "简介", type: "textarea" },
      { key: "air_date", label: "播出日期", type: "text", placeholder: "2026-07-09" },
      { key: "player_count", label: "玩家人数", type: "text", placeholder: "21" },
      { key: "duration_minutes", label: "时长（分钟）", type: "text", placeholder: "70" },
      { key: "status", label: "状态", type: "select", options: ["热播中", "已完结"] },
      { key: "bilibili_link", label: "B 站链接", type: "text" },
      {
        key: "cover_image",
        label: "封面路径",
        type: "text",
        placeholder: "/images/covers/xxx.jpg（图片需先提交到仓库 public/images/covers/）",
      },
      { key: "episode_number", label: "期号", type: "number" },
      {
        key: "main_category_id",
        label: "所属系列",
        type: "select",
        ref: { file: "episode_main_categories", valueKey: "id", labelKey: "name" },
      },
      {
        key: "sub_category_id",
        label: "所属季",
        type: "select",
        ref: { file: "episode_sub_categories", valueKey: "id", labelKey: "name" },
      },
      { key: "sort_order", label: "排序", type: "number" },
      { key: "id", label: "ID", type: "text", readonly: true },
    ],
  },
  {
    key: "episode_links",
    label: "期数链接",
    file: "src/data/episode_links.json",
    hasId: true,
    list: ["title", "episode_number", "link_url"],
    fields: [
      { key: "title", label: "期标题", type: "text", required: true, placeholder: "S5E3" },
      { key: "episode_number", label: "期号", type: "number" },
      { key: "link_url", label: "B 站链接", type: "text" },
      { key: "sort_order", label: "排序", type: "number" },
      { key: "id", label: "ID", type: "text", readonly: true },
    ],
  },
  {
    key: "episode_main_categories",
    label: "系列分类",
    file: "src/data/episode_main_categories.json",
    hasId: true,
    list: ["name", "sort_order"],
    fields: [
      { key: "name", label: "名称", type: "text", required: true },
      { key: "sort_order", label: "排序", type: "number" },
      { key: "id", label: "ID", type: "text", readonly: true },
    ],
  },
  {
    key: "episode_sub_categories",
    label: "季分类",
    file: "src/data/episode_sub_categories.json",
    hasId: true,
    list: ["name", "sort_order"],
    fields: [
      { key: "name", label: "名称", type: "text", required: true },
      {
        key: "main_category_id",
        label: "所属系列",
        type: "select",
        ref: { file: "episode_main_categories", valueKey: "id", labelKey: "name" },
      },
      { key: "sort_order", label: "排序", type: "number" },
      { key: "id", label: "ID", type: "text", readonly: true },
    ],
  },
  {
    key: "rules",
    label: "游戏规则",
    file: "src/data/rules.json",
    hasId: false,
    list: ["title", "desc"],
    fields: [
      { key: "title", label: "板块标题", type: "text", required: true },
      { key: "desc", label: "板块说明", type: "text" },
      { key: "items", label: "条目（每行一条）", type: "lines" },
    ],
  },
  {
    key: "memes",
    label: "梗百科",
    file: "src/data/memes.json",
    hasId: true,
    list: ["title", "category", "episode"],
    fields: [
      { key: "title", label: "梗名称", type: "text", required: true },
      {
        key: "category",
        label: "分类",
        type: "select",
        ref: { file: "meme_categories", valueKey: "name", labelKey: "name" },
      },
      { key: "episode", label: "出自期数", type: "text", placeholder: "全员逃亡中 / 逃亡中S2E1" },
      { key: "description", label: "内容", type: "textarea" },
      { key: "bilibili_link", label: "B 站链接", type: "text" },
      { key: "sort_order", label: "排序", type: "number" },
      { key: "id", label: "ID", type: "text", readonly: true },
    ],
  },
  {
    key: "meme_categories",
    label: "梗分类",
    file: "src/data/meme_categories.json",
    hasId: true,
    list: ["name", "sort_order"],
    fields: [
      { key: "name", label: "名称", type: "text", required: true },
      { key: "sort_order", label: "排序", type: "number" },
      { key: "id", label: "ID", type: "text", readonly: true },
    ],
  },
  {
    key: "rankings",
    label: "排行榜",
    file: "src/data/rankings.json",
    hasId: true,
    list: ["player_id", "season", "episode_number", "total_score", "rank"],
    fields: [
      {
        key: "player_id",
        label: "玩家",
        type: "select",
        required: true,
        ref: { file: "players", valueKey: "id", labelKey: "name" },
      },
      { key: "season", label: "季", type: "number", required: true },
      { key: "episode_number", label: "期数", type: "number", required: true },
      { key: "steps", label: "步数（0 = 未统计）", type: "number" },
      { key: "total_score", label: "总积分", type: "number", required: true },
      { key: "rank", label: "名次", type: "number" },
      { key: "sort_order", label: "排序", type: "number" },
      { key: "id", label: "ID", type: "text", readonly: true },
    ],
  },
  {
    key: "players",
    label: "玩家档案",
    file: "src/data/players.json",
    hasId: true,
    list: ["name", "gender", "episodes", "declaration"],
    fields: [
      { key: "name", label: "昵称", type: "text", required: true },
      { key: "gender", label: "性别", type: "select", options: ["男", "女"] },
      { key: "episodes", label: "参赛期数", type: "number" },
      { key: "win_episodes", label: "夺冠期数", type: "number" },
      { key: "declaration", label: "平台/来源", type: "text", placeholder: "Bilibili-游戏区" },
      {
        key: "avatar",
        label: "头像路径",
        type: "text",
        placeholder: "/images/avatars/xxx.png（图片需先提交到仓库 public/images/avatars/）",
      },
      {
        key: "episode_list",
        label: "参赛期数列表",
        type: "text",
        placeholder: '[13, 20]（JSON 数组，用于弹窗期数链接）',
      },
      { key: "bilibili_link", label: "B 站主页", type: "text" },
      { key: "sort_order", label: "排序", type: "number" },
      { key: "id", label: "ID", type: "text", readonly: true },
    ],
  },
  {
    key: "hunters",
    label: "猎人档案",
    file: "src/data/hunters.json",
    hasId: true,
    list: ["name", "code"],
    fields: [
      { key: "name", label: "名称", type: "text", required: true },
      { key: "code", label: "编号", type: "text", placeholder: "A001MM" },
      {
        key: "avatar",
        label: "头像路径",
        type: "text",
        placeholder: "/images/avatars/xxx.png",
      },
      { key: "bilibili_link", label: "B 站主页", type: "text" },
      { key: "sort_order", label: "排序", type: "number" },
      { key: "id", label: "ID", type: "text", readonly: true },
    ],
  },
];
